version: 2.1

commands:
  install-packaged-autonormalize:
    description: "install autonormalize from source distribution"
    steps:
      - run : |
          source test_env/bin/activate
          python setup.py sdist
          AUTONORMALIZE_VERSION=$(python setup.py --version)
          tar -zxvf "dist/autonormalize-${AUTONORMALIZE_VERSION}.tar.gz"
          pip install -e "autonormalize-${AUTONORMALIZE_VERSION}/"
          pip install -r "autonormalize-${AUTONORMALIZE_VERSION}/test-requirements.txt"
  run-packaged-tests:
    description: "run unit tests on packaged testing files"
    steps:
      - run: |
          source test_env/bin/activate
          cd "autonormalize-$(python setup.py --version)/"
          pytest

jobs:
  "python-27":
    working_directory: ~/auto-norm
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-autonormalize
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run-packaged-tests

  "python-35":
    working_directory: ~/auto-norm
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-autonormalize
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run-packaged-tests

  "python-36":
    working_directory: ~/auto-norm
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-autonormalize
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run-packaged-tests

  "python-37":
    working_directory: ~/auto-norm
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-autonormalize
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run-packaged-tests


workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - "python-27"
      - "python-35"
      - "python-36"
      - "python-37"
