version: 2.1

executors:
  python:
    parameters:
      image_tag:
        type: string
        default: "python:3.7"
    docker:
      - image: circleci/<< parameters.image_tag >>

commands:
  installation:
    steps:
      - checkout
      - run:
          name: "Package Installation to Virtual Environment"
          command: |
            python setup.py sdist
            PACKAGE=$(python setup.py --fullname)
            tar -zxvf "dist/${PACKAGE}.tar.gz"
            mv ${PACKAGE} package && cd package
            virtualenv package -q
            source package/bin/activate
            pip install -e . --progress-bar off
            pip install -r test-requirements.txt --progress-bar off

jobs:
  lint_tests:
    working_directory: ~/autonormalize
    parameters:
      image_tag:
        type: string
        default: "python:3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: "Lint Tests"
          command: |
            source env/bin/activate
            cd package && make lint-tests

  unit_tests:
    working_directory: ~/autonormalize
    parameters:
      image_tag:
        type: string
        default: "python:3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: "Unit Tests"
          command: |
            source env/bin/activate
            cd package && make unit-tests

  entry_point_test:
    working_directory: ~/autonormalize
    parameters:
      image_tag:
        type: string
        default: "python:3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: "Entry Point Test"
          command: |
            source env/bin/activate
            cd package && make entry-point-test

workflows:
  version: 2
  "Integration Tests":
    jobs:
      - lint_tests:
          name: "Lint Tests - Python 3.5"
          image_tag: "python:3.5"
      - lint_tests:
          name: "Lint Tests - Python 3.6"
          image_tag: "python:3.6"
      - lint_tests:
          name: "Lint Tests - Python 3.7"
          image_tag: "python:3.7"
      - unit_tests:
          name: "Unit Tests - Python 3.5"
          image_tag: "python:3.5"
      - unit_tests:
          name: "Unit Tests - Python 3.6"
          image_tag: "python:3.6"
      - unit_tests:
          name: "Unit Tests - Python 3.7"
          image_tag: "python:3.7"
      - entry_point_test:
          name: "Entry Point Test - Python 3.5"
          image_tag: "python:3.5"
      - entry_point_test:
          name: "Entry Point Test - Python 3.6"
          image_tag: "python:3.6"
      - entry_point_test:
          name: "Entry Point Test - Python 3.7"
          image_tag: "python:3.7"
